Repository kubeflow/mcp-apache-spark-history-server, pull requests merged in 2025-09, with the labels that each got.

#110 feat: Replacing Github Org from DeepDiagnostix-AI to Kubeflow
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  TESTING.md
  deploy/kubernetes/helm/mcp-apache-spark-history-server/Chart.yaml
  deploy/kubernetes/helm/mcp-apache-spark-history-server/values.yaml
  examples/aws/emr/README.md
  examples/aws/glue/README.md
  examples/integrations/amazon-q-cli/README.md
  examples/integrations/claude-desktop/README.md
  examples/integrations/kiro/README.md
  pyproject.toml
Labels: size/L, lgtm, approved

#113 configurable configuration file path
  README.md
  src/spark_history_mcp/core/main.py
Labels: lgtm, approved, size/M

#114 sync gh and pypi releases
  .github/workflows/release.yaml
  README.md
Labels: size/S, lgtm, approved
